---
title: "Atividade III - SME0821"
output: pdf_document
date: '2022-07-13'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(survival)
library(survminer)
library(pander)
library(biostat3)
library(rankhazard)
```

# Conjunto de dados utilizado
```{r}
df <- survminer::myeloma %>% rownames_to_column %>% tibble
# Substituindo o indicador de censura por um tipo booleano
df$event <- as.logical(df$event)
head(df)
str(df)
```

```{r}
# Cox proportional hazard model
cph.df <- coxph(Surv(time,event)~CCND1+DEPDC1+TP53+WHSC1,df)
summary(cph.df)
```

```{r}
# rankhazardplot()
(dfCopy <- df)
dfCopy$event <- ifelse(dfCopy$event == FALSE,0,1)

str(dfCopy)
(dfCopyCopy = subset(dfCopy, select = -c(molecular_group,chr1q21_status,treatment,rowname)))

```


## Transformando os dados booleanos em dados numericos devido a erro na funcao

# Visualization of relative importance of covariates
```{r}
(cph.full <- coxph(Surv(time,event)~CCND1+DEPDC1+TP53+WHSC1, dfCopyCopy, x=TRUE))
rankhazardplot(cph.full,data=dfCopyCopy)
```

# Linha 18: qual covariaveis utilizar; Resposta: são as covariaveis que nao 
# se cruzam na curva de sobrevivencia: CCND1, DEPDC1, TP53, WHSC1

# Test the proportional hazards assumption

```{r}
cox.zph(cph.full)
par(mfrow=c(1,1))
plot(cox.zph(cph.full))

km_fit <- survfit(Surv(time, event) ~ 1, data = df)
km_fit
```
